CREATE TABLE post
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message     VARCHAR(255),
    customer_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

ALTER TABLE post
    ADD CONSTRAINT FK_POST_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);