CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE customer_role
(
    customer_id BIGINT NOT NULL,
    role_id     BIGINT NOT NULL
);

ALTER TABLE customer_role
    ADD CONSTRAINT fk_cusrol_on_customer FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE customer_role
    ADD CONSTRAINT fk_cusrol_on_role FOREIGN KEY (role_id) REFERENCES role (id);